name = "lustre_ui"
version = "1.0.0-rc.1"
description = "A collection of components and design tokens for building Lustre apps."
target = "javascript"

licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre_ui" }
links = [
    { title = "Website", href = "https://lustre.build" },
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = ["lustre_ui/*", "lustre/ui/*/*"]

[dependencies]
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_stdlib = ">= 0.67.0 and < 2.0.0"
lustre = ">= 5.5.1 and < 6.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"

[dev-dependencies]
lustre_fable = { git = "https://github.com/lustre-labs/fable.git", ref = "main" }

[tools.lustre.dev]
watch = ["dev"]
